### ISSUE TITLE
Server downtime

### ISSUE THREAD

**Issue by markd315** [mrazza/path-data#11]
![image](https://user-images.githubusercontent.com/2876300/140413271-de84ba89-480f-4e9e-a772-119e741c0faa.png)
Not sure if you are aware or not, but the API has been down for a few days now.

This is what your status page shows, not sure if a code issue or an operational one.

https://jsfiddle.net/a6Ls5w8b/9/

Here are some unrelated improvements I made to your jsfiddle example from the reddit post in case you are interested. Shows train direction, line color etc in the view.

**Comment by mrazza** [comment]
Sorry folks. Was struggling to find time to address this.

Just started looking at it.

**Comment by mrazza** [comment]
Fixed in d1bad585651830f9f2db8576c9029a50b61ed7ae

**Comment by mrazza** [comment]
Please re-open if this repros.
