### ISSUE TITLE
Calls to routes API throwing exceptions

### ISSUE THREAD

**Issue by deegoldberg** [mrazza/path-data#12]
Thank you for putting together this amazing resource! I've encountered an issue with the routes API described in `README.md`.

* To reproduce: Open https://path.api.razza.dev/v1/routes/ in a web browser.

* Expected result: Return a list of routes

* Actual result: 
```
{
 "code": 2,
 "message": "Exception was thrown by handler.",
 "details": []
}
```

**Comment by mrazza** [comment]
Exception:
```
2022-02-07 18:03:22.745 +00:00 [Error] (/GrpcExceptionInterceptor.UnaryServerHandler:34) Unexpected error in gRPC handler for PathApi.Server.GrpcApi.V1.RoutesApi.
System.Collections.Generic.KeyNotFoundException: The given key '11048' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PathApi.Server.PathServices.PathSqlDbRepository.GetRoutes() in /home/mrazza/sources/path-data/server/PathServices/PathSqlDbRepository.cs:line 157
   at PathApi.Server.GrpcApi.V1.RoutesApi.GetAllRoutes() in /home/mrazza/sources/path-data/server/GrpcApi/V1/RoutesApi.cs:line 82
   at PathApi.Server.GrpcApi.V1.RoutesApi.ListRoutes(ListRoutesRequest request, ServerCallContext context) in /home/mrazza/sources/path-data/server/GrpcApi/V1/RoutesApi.cs:line 50
   at PathApi.Server.GrpcExceptionInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation)
```

**Comment by mrazza** [comment]
API Route Enum to PATH SQL Database ID relationship needs updating:
https://github.com/mrazza/path-data/blob/9e7880f04af55fd91107236d9259c590337e8525/server/PathServices/RouteMappings.cs#L16

Unclear if I'll get to this today or later in the week.

**Comment by deegoldberg** [comment]
Thanks for the quick reply! 

I'll observe that this past weekend, the PATH system had an unusual route configuration due to track work. Trains traveling between Journal Square and 33rd bypassed Hoboken and PATH ran a shuttle train for service between Newport and Hoboken. More info here https://www.panynj.gov/path/en/schedules-maps/no-direct-hob.html . But perhaps this is not the issue given that service is back to normal and the exception is still happening?

**Comment by mrazza** [comment]
No, this does indeed sound promising. This configuration data is not pushed consistently, instead there's a static SQLite database that the PATH produces. It's possible that this is, indeed, a new route configuration we've never seen before present in it and either PATH has not yet removed it or does not intend to. Both are valid outcomes.

The question is whether this route will be used again or frequently and is worth adding to the API contract. I know a bunch of folks, especially in JC, were happy to not be forced to HOB so it's unclear whether this can come back. Either way, I should make this code tolerant of new routes popping up.

**Comment by deegoldberg** [comment]
Perhaps `11048` is the key for the Hoboken-Newport shuttle route? If so, a quick fix might be something like
```
public static readonly ReadOnlyDictionary<string, Route> DatabaseIdToRoute =
            new ReadOnlyDictionary<string, Route>(new Dictionary<string, Route>()
            {
                { "1024", Route.Jsq33Hob },
                { "859", Route.Hob33 },
                { "860", Route.HobWtc },
                { "861", Route.Jsq33 },
                { "862", Route.NwkWtc },
                { "11048", Route.NptHob }
            });
```

**Comment by mrazza** [comment]
`151|11048|PATH|Newport - Hoboken Shuttle Train||2||8c3c96|ffffff|6|15`

We have a winner.
