### ISSUE TITLE
API not working since this morning 9:30 am 

### ISSUE THREAD

**Issue by balajeek** [mrazza/path-data#14]
I have some automations that run on node-red that uses this api to get train timings, that get activated only when i commute, after the long weekend this morning 9:30 am on my way to work i did not get the notifications and looking at it now 12:50pm i see the api does not run.  

Anyone knows whats happening?

**Comment by mrazza** [comment]
Current guess is an issue with the production load balancer. Will need to investigate later.

Thanks for opening.

**Comment by balajeek** [comment]
Thank you.

**Comment by balajeek** [comment]
any luck?

**Comment by mrazza** [comment]
Sorry folks. Hope to look at this soon.

**Comment by balajeek** [comment]
No worries.
In meantime i was digging thru the path official site to see how they showed their real-time departures, and i figured out the json file they use which make me convenient becaz all i needed is the json to use with my node-red.  I am all good now.  
But hope to see your api working soon.  Thank you.

**Comment by balajeek** [comment]
https://www.panynj.gov/bin/portauthority/ridepath.json

**Comment by mrazza** [comment]
Nice!

**Comment by markd315** [comment]
I for one am a little bit confused now because I thought the original motivation for this API was to cache and quickly retrieve data since the PATH app uses a slow pub/sub method to get the data.

Is this json endpoint new? Is it retrieving only schedule data and not real-time? At this point, what are the relative disadvantages of the official data vs this API, aside from me doing the dev work to reingest and parse it?

**Comment by balajeek** [comment]
I started using the api just recently about a month ago, and i could precisely tell what station i want and it does give me that in json format.  when it stopped working and couple of days later i noticed path official site have the real-time data showing, so i wondered it has to come from some where, so i started looking it chrome developer console and ended up find this think that contain all the stations and timings and it get updated real-time.

May be its new !

**Comment by markd315** [comment]
As long as it has real time data I might consider migrating my usage to it as well thank you for the context

**Comment by cannondale0815** [comment]
> https://www.panynj.gov/bin/portauthority/ridepath.json

This works great in Home Assistant -- thanks @balajeek !

**Comment by cannondale0815** [comment]
@balajeek I have the below in my configuration.yaml, and it refreshes every 45 seconds. I don't see a reason why I should limit my polling to only certain times of the day, so every 45 seconds is ok with me (I did the same with mrazza's API before).

FYI: I am only interested in two trains, and their arrival at one particular station.

```
rest:
  - resource: https://www.panynj.gov/bin/portauthority/ridepath.json
    scan_interval: 45
    sensor:
      - name: "PATH train 1 lineName"
        value_template: >
          {% set stationGRV = value_json.results | selectattr("consideredStation","eq","GRV") | first %}
          {% set destinationToNY = stationGRV.destinations | selectattr("label", "eq", "ToNY") | first %}
          {% set headSignTrain1 = destinationToNY.messages[0].headSign %}
          {{ headSignTrain1 }}
      - name: "PATH train 1 projectedArrival"
        value_template: >
          {% set stationGRV = value_json.results | selectattr("consideredStation","eq","GRV") | first %}
          {% set destinationToNY = stationGRV.destinations | selectattr("label", "eq", "ToNY") | first %}
          {% set arrivalTimeTrain1 = destinationToNY.messages[0].arrivalTimeMessage %} 
          {{ arrivalTimeTrain1 }}
      - name: "PATH train 2 lineName"
        value_template: >
          {% set stationGRV = value_json.results | selectattr("consideredStation","eq","GRV") | first %}
          {% set destinationToNY = stationGRV.destinations | selectattr("label", "eq", "ToNY") | first %}
          {% set headSignTrain2 = destinationToNY.messages[1].headSign %}
          {{ headSignTrain2 }}
      - name: "PATH train 2 projectedArrival"
        value_template: >
          {% set stationGRV = value_json.results | selectattr("consideredStation","eq","GRV") | first %}
          {% set destinationToNY = stationGRV.destinations | selectattr("label", "eq", "ToNY") | first %}
          {% set arrivalTimeTrain2 = destinationToNY.messages[1].arrivalTimeMessage %}
          {{ arrivalTimeTrain2 }}
```

**Comment by markd315** [comment]
For anyone who just wants a version of Matt's old real time jsfiddle working again I adapted it to consume the new data source. Cors proxy was the hard part had to try a bunch of free ones to get it working.

https://jsfiddle.net/3hgm9Lrv/3/show

Can also use it as an example of how to fetch and parse in this new format if you want.

**Comment by markd315** [comment]
^ Note that I have just experimentally determined this source is not providing the real-time data but just the schedule information. So it's a stopgap solution.

**Comment by balajeek** [comment]
Thats great the web version is live again.  wondering is it possible that i could modify a copy of your jsfiddle to keep only two stations i need, so i could in corporate in an iframe for my use.  thanks.

**Comment by markd315** [comment]
> Thats great the web version is live again.  wondering is it possible that i could modify a copy of your jsfiddle to keep only two stations i need, so i could incorporate in an iframe for my use.  thanks.

yeah any of these are essentially open source you can modify it to your needs without asking anyone. Think you just put like /edit for the url instead of /show.

**Comment by cannondale0815** [comment]
> 

It 

> ^ Note that I have just experimentally determined this source is not providing the real-time data but just the schedule information. So it's a stopgap solution.

It never actually provided super reliable data to begin with. Even if it said that it was on time, the train often wasn't. And if it was saying "delayed" with an arrival time, who ever knew what that meant -- does it mean the arrival time is the actual time, or the scheduled time but delayed.

**Comment by kerrickstaley** [comment]
The URL https://www.panynj.gov/bin/portauthority/ridepath.json is inaccessible from a web app due to CORS [1]. So mrazza's API is still helpful at least for me.

[1] The error I get is
```
Access to fetch at 'https://www.panynj.gov/bin/portauthority/ridepath.json' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by markd315** [comment]
> The URL https://www.panynj.gov/bin/portauthority/ridepath.json is inaccessible from a web app due to CORS [1]. So mrazza's API is still helpful at least for me.
> 
> [1] The error I get is
> ```
> Access to fetch at 'https://www.panynj.gov/bin/portauthority/ridepath.json' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> ```

Yes, refer to my comments. I would still love to get the Matt API up and running again because it has the real-time data. If all you need is a way to get the schedule data in JSON you can still consume the site even though the CORS is effed by using a proxy. See my latest jsfiddle for an example of how to do that if you need.

**Comment by kerrickstaley** [comment]
The ridepath.json URL has real-time arrival information; it doesn’t just use a schedule. However, it seems like it’s not as good as path-data because the data it outputs is lagged by ~80 seconds.

I blogged about this in more detail at https://www.kerrickstaley.com/2022/11/26/timeline-of-a-train-departure

**Comment by mrazza** [comment]
Sorry folks.

Life and work got in the way and this should be fixed now. Please let me know if it's not.
