### ISSUE TITLE
https://path.api.razza.dev/v1/stations/ninth_street/realtime is not up

### ISSUE THREAD

**Issue by celron** [mrazza/path-data#25]
Greetings mrazza,
I'm not sure if you are still maintaining the system that you have, however I have been using your api, and for some reason it is not currently up. I'm not familiar with .net but will take a look to see if I troubleshoot it.

**Comment by b264** [comment]
It's also down for me

**Comment by celron** [comment]
the api actually appears to work, but inconsistently.

**Comment by celron** [comment]
Suddenly, the api is now working. I suspect that the data behind it had some issues. NJ Transit did some changes to the portal which may mean some changes to the underlying infrastructure. Closing
