### ISSUE TITLE
New API consumer

### ISSUE THREAD

**Issue by jamespfennell** [mrazza/path-data#6]
I wanted to let you know about a new consumer of your API, and couldn't find another way to contact you!

This week I deployed a project that reads your API and outputs a public feed in the GTFS Realtime format. I'm hitting your API every 5 seconds which I hope is okay. More information is on the project repo: https://github.com/jamespfennell/path-train-gtfs-realtime

The motivation is to enable applications that already work with GTFS "natively" to use the data without any app-specific logic. So, for example, the backend of my web app which previously just had NYC Subway data now has PATH data with no customization required more or less: https://www.realtimerail.nyc/transiter/v0.4/systems

Thanks for the API, it's really great to be able to get this data.

**Comment by mrazza** [comment]
Nice. No concerns. I stayed away from realtime GTFS Realtime format as it seemed kind of pointless given the limited data I was able to pull. Cool to be proven wrong on that.

**Comment by jamespfennell** [comment]
Awesome. Thanks for the line in the readme!
