### ISSUE TITLE
API not working anymore?

### ISSUE THREAD

**Issue by mraess** [mrazza/path-data#7]
Hi @mrazza has the API stopped working recently? The test app doesn't seem to be showing updated data either.

**Comment by mrazza** [comment]
There's a bug causing CPU on the VM to peg at 100% and make the API inoperable. Seems to be related to reconnections. I am struggling to find time to investigate.

**Comment by mraess** [comment]
@mrazza thanks for the quick update here. I was just wondering b/c I've built a Real-time tracker display with an ESP8266 and all of a sudden it stopped working. Do you mind letting me know once you figure out what the problem is?

**Comment by mrazza** [comment]
Will use this as a tracking bug for the issue.

@wgraham17 FYI

**Comment by mraess** [comment]
@mrazza awesome, thanks!

**Comment by wgraham17** [comment]
@mrazza Do you have logs anywhere accessible? Not sure how that would get
stuck eating the whole core...

**Comment by mrazza** [comment]
Logs don't seem to indicate a real problem. Will likely need to profile the application to understand what thread(s) are consuming CPU and what they're doing. Logs only show reconnections (and correctly rate limited reconnections).

https://gist.github.com/mrazza/bbf9a663a3b17b74da1c4b7a029f03ea

**Comment by mraess** [comment]
@mrazza @wgraham17 are there any updates on a potential fix for this problem?

**Comment by mrazza** [comment]
I'm in the process of moving cloud providers. I've changed the the DNS record for the GRPC endpoints and will monitor stability.

**Comment by mrazza** [comment]
Moving over HTTP DNS records now. I expect this not to be perfectly smooth as I issue a new SSL cert.

**Comment by mrazza** [comment]
Closing for now. Please re-open if this repros.

**Comment by mraess** [comment]
@mrazza Thanks for the update! Much appreciated. I'll let you know if it works again on my end.
